# Copyright (c) Meta Platforms, Inc. and affiliates.

REPRESENTATION_IDCS = {
    "pos_left": (0, 3),
    "pos_right": (3, 6),
    "global_orient_l": (30, 36),
    "global_orient_r": (60, 66),
    "pca_left": (6, 30),
    "pca_right": (36, 60),
    "sdf_left": (66, 87),
    "sdf_right": (87, 108),
    "object_pose": (108, 117),
}

REPRESENTATION_IDCS_SIMPLE = {
    "pos_left": (0, 3),
    "pos_right": (3, 6),
    "global_orient_l": (6, 12),
    "global_orient_r": (12, 18),
    "object_pose": (18, 27),
}

SIMPLE_REPR_INDICES = [
    0, 1, 2,
    3, 4, 5,
    30, 31, 32, 33, 34, 35,
    60, 61, 62, 63, 64, 65,
    108, 109, 110, 111, 112, 113, 114, 115, 116,
]

OBJECT_LIST = ['cylinderlarge', 'mug', 'elephant', 'hand', 'cubelarge', 'stanfordbunny', 'airplane', 'alarmclock', 'banana', 'body', 'bowl', 'cubesmall', 'cup', 'doorknob', 'cubemedium',
             'eyeglasses', 'flashlight', 'flute', 'gamecontroller', 'hammer', 'headphones', 'knife', 'lightbulb', 'mouse', 'phone', 'piggybank', 'pyramidlarge', 'pyramidsmall', 'pyramidmedium',
             'duck', 'scissors', 'spherelarge', 'spheresmall', 'stamp', 'stapler', 'table', 'teapot', 'toruslarge', 'torussmall', 'train', 'watch', 'cylindersmall', 'waterbottle', 'torusmedium',
             'cylindermedium', 'spheremedium', 'wristwatch', 'wineglass', 'camera', 'binoculars', 'fryingpan', 'toothpaste', 'apple', 'toothbrush']

OBJECT_LIST_NEW = ['large cylinder', 'mug', 'elephant', 'hand', 'large cube', 'stanfordbunny', 'airplane', 'alarmclock', 'banana', 'body', 'bowl', 'small cube', 'cup', 'doorknob', 'medium cube',
             'eyeglasses', 'flashlight', 'flute', 'gamecontroller', 'hammer', 'headphones', 'knife', 'lightbulb', 'mouse', 'phone', 'piggybank', 'large pyramid', 'small pyramid', 'medium pyramid',
             'duck', 'scissors', 'large sphere', 'small sphere', 'stamp', 'stapler', 'table', 'teapot', 'large torus', 'small torus', 'train', 'watch', 'small cylinder', 'waterbottle', 'medium torus',
             'medium cylinder', 'medium sphere', 'wristwatch', 'wineglass', 'camera', 'binoculars', 'fryingpan', 'toothpaste', 'apple', 'toothbrush']

YCB_LIST =    ['large can', 'drill', 'mug', 'marker',
                'pitcher', 'scissors', 'clamp', 'block',
                'brick', 'bowl', 'cracker box', 'large box',
                'cereal box',
                'small can', 'sugar box', 'mustard bottle',
                'tuna fish can', 'pudding box', 'can',
                'gelatin box', 'potted meat can',
                'banana', 'bleach cleanser']

OBJ_TO_YCB = {
    'large can': '002_master_chef_can',
    'drill': '035_power_drill',
    'mug': '025_mug',
    'marker': '040_large_marker',
    'pitcher': '019_pitcher_base',
    'scissors': '037_scissors',
    'clamp': '052_extra_large_clamp',
    'block': '036_wood_block',
    'brick': '061_foam_brick',
    'bowl': '024_bowl',
    'cracker box': '003_cracker_box',
    'large box': '003_cracker_box',
    'cereal box': '003_cracker_box',
    'small can': '005_tomato_soup_can',
    'can': '005_tomato_soup_can',
    'sugar box': '004_sugar_box',
    'mustard bottle': '006_mustard_bottle',
    'tuna fish can': '007_tuna_fish_can',
    'pudding box': '008_pudding_box',
    'gelatin box': '009_gelatin_box',
    'potted meat can': '010_potted_meat_can',
    'banana': '011_banana',
    'bleach cleanser': '021_bleach_cleanser',
}

OBJ_TO_YCB_MESH = {
    'large can': '002_master_chef_can/master_chef_can.stl',
    'drill': '035_power_drill/textured.obj',
    'mug': '025_mug/mug.stl',
    'marker': '040_large_marker/textured.obj',
    'pitcher': '019_pitcher_base/textured.obj',
    'scissors': '037_scissors/textured.obj',
    'clamp': '052_extra_large_clamp/textured.obj',
    'block': '036_wood_block/textured.obj',
    'brick': '061_foam_brick/textured.obj',
    'bowl': '024_bowl/textured.obj',
    'cracker box': '003_cracker_box/cracker_box.stl',
    'cereal box': '003_cracker_box/cracker_box.stl',
    'large box': '003_cracker_box/cracker_box.stl',
    'small can': '005_tomato_soup_can/tomato_soup_can.stl',
    'can': '005_tomato_soup_can/tomato_soup_can.stl',
    'sugar box': '004_sugar_box/sugar_box.stl',
    'mustard bottle': '006_mustard_bottle/mustard_bottle.stl',
    'tuna fish can': '007_tuna_fish_can/textured.obj',
    'pudding box': '008_pudding_box/pudding_box.stl',
    'gelatin box': '009_gelatin_box/gelatin_box.stl',
    'potted meat can': '010_potted_meat_can/potted_meat_can.stl',
    'banana': '011_banana/banana.stl',
    'bleach cleanser': '021_bleach_cleanser/textured.obj',
}

OBJECT_ORIGINAL2NEW_DICT = {
    'cylinderlarge': 'large cylinder',
    'mug': 'mug',
    'elephant': 'elephant',
    'hand': 'hand',
    'cubelarge': 'large cube',
    'stanfordbunny': 'stanfordbunny',
    'airplane': 'airplane',
    'alarmclock': 'alarmclock',
    'banana': 'banana',
    'body': 'body',
    'bowl': 'bowl',
    'cubesmall': 'small cube',
    'cup': 'cup',
    'doorknob': 'doorknob',
    'cubemedium': 'medium cube',
    'eyeglasses': 'eyeglasses',
    'flashlight': 'flashlight',
    'flute': 'flute',
    'gamecontroller': 'gamecontroller',
    'hammer': 'hammer',
    'headphones': 'headphones',
    'knife': 'knife',
    'lightbulb': 'lightbulb',
    'mouse': 'mouse',
    'phone': 'phone',
    'piggybank': 'piggybank',
    'pyramidlarge': 'large pyramid',
    'pyramidsmall': 'small pyramid',
    'pyramidmedium': 'medium pyramid',
    'duck': 'duck',
    'scissors': 'scissors',
    'spherelarge': 'large sphere',
    'spheresmall': 'small sphere',
    'stamp': 'stamp',
    'stapler': 'stapler',
    'table': 'table',
    'teapot': 'teapot',
    'toruslarge': 'large torus',
    'torussmall': 'small torus',
    'train': 'train',
    'watch': 'watch',
    'cylindersmall': 'small cylinder',
    'waterbottle': 'waterbottle',
    'torusmedium': 'medium torus',
    'cylindermedium': 'medium cylinder',
    'spheremedium': 'medium sphere',
    'wristwatch': 'wristwatch',
    'wineglass': 'wineglass',
    'camera': 'camera',
    'binoculars': 'binoculars',
    'fryingpan': 'fryingpan',
    'toothpaste': 'toothpaste',
    'apple': 'apple',
    'toothbrush': 'toothbrush'
}

IDX_TO_YCB_NAME = {
    1: 'can',
    2: 'box',
    3: 'sugar box',
    4: 'soup can',
    5: 'bottle',
    6: 'tuna can',
    7: 'pudding box',
    8: 'gelatin box',
    9: 'meat can',
    10: 'banana',
    11: 'pitcher',
    12: 'cleanser',
    13: 'bowl',
    14: 'mug',
    15: 'drill',
    16: 'block',
    17: 'scissors',
    18: 'marker',
    20: 'clamp',
    21: 'brick',
}



IDX_TO_YCB_ORIG_NAME = {
    1: '002_master_chef_can',
    2: '003_cracker_box',
    3: '004_sugar_box',
    4: '005_tomato_soup_can',
    5: '006_mustard_bottle',
    6: '007_tuna_fish_can',
    7: '008_pudding_box',
    8: '009_gelatin_box',
    9: '010_potted_meat_can',
    10: '011_banana',
    11: '019_pitcher_base',
    12: '021_bleach_cleanser',
    13: '024_bowl',
    14: '025_mug',
    15: '035_power_drill',
    16: '036_wood_block',
    17: '037_scissors',
    18: '040_large_marker',
    20: '052_extra_large_clamp',
    21: '061_foam_brick',
}

OBJECT_NEW2ORIGINAL_DICT = {
    'large cylinder': 'cylinderlarge',
    'mug': 'mug',
    'elephant': 'elephant',
    'hand': 'hand',
    'large cube': 'cubelarge',
    'stanfordbunny': 'stanfordbunny',
    'airplane': 'airplane',
    'alarmclock': 'alarmclock',
    'banana': 'banana',
    'body': 'body',
    'bowl': 'bowl',
    'small cube': 'cubesmall',
    'cup': 'cup',
    'doorknob': 'doorknob',
    'medium cube': 'cubemedium',
    'eyeglasses': 'eyeglasses',
    'flashlight': 'flashlight',
    'flute': 'flute',
    'gamecontroller': 'gamecontroller',
    'hammer': 'hammer',
    'headphones': 'headphones',
    'knife': 'knife',
    'lightbulb': 'lightbulb',
    'mouse': 'mouse',
    'phone': 'phone',
    'piggybank': 'piggybank',
    'large pyramid': 'pyramidlarge',
    'small pyramid': 'pyramidsmall',
    'medium pyramid': 'pyramidmedium',
    'duck': 'duck',
    'scissors': 'scissors',
    'large sphere': 'spherelarge',
    'small sphere': 'spheresmall',
    'stamp': 'stamp',
    'stapler': 'stapler',
    'table': 'table',
    'teapot': 'teapot',
    'large torus': 'toruslarge',
    'small torus': 'torussmall',
    'train': 'train',
    'watch': 'watch',
    'small cylinder': 'cylindersmall',
    'waterbottle': 'waterbottle',
    'medium torus': 'torusmedium',
    'medium cylinder': 'cylindermedium',
    'medium sphere': 'spheremedium',
    'wristwatch': 'wristwatch',
    'wineglass': 'wineglass',
    'camera': 'camera',
    'binoculars': 'binoculars',
    'fryingpan': 'fryingpan',
    'toothpaste': 'toothpaste',
    'apple': 'apple',
    'toothbrush': 'toothbrush'
}

HOT3D_OBJECT_LIST = [
    'aria_small', 'birdhouse_toy', 'bottle_bbq', 'bottle_mustard', 'bottle_ranch',
    'bowl', 'can_parmesan', 'can_soup', 'can_tomato_sauce', 'carton_milk', 'carton_oj',
    'cellphone', 'coffee_pot', 'dino_toy', 'dumbbell_5lb', 'dvd_remote', 'flask',
    'food_vegetables', 'food_waffles', 'holder_black', 'holder_gray', 'keyboard',
    'mouse', 'mug_patterned', 'mug_white', 'plate_bamboo', 'potato_masher', 'puzzle_toy',
    'spatula_red', 'spoon_wooden', 'vase', 'whiteboard_eraser', 'whiteboard_marker'
]
